# Netlify Configuration File
# Place this file in the root directory of your project

[build]
  # Build command to run
  command = "npm run build"
  
  # Directory to publish (where the built files are)
  publish = "build"

[build.environment]
  # Set CI to false to treat warnings as warnings, not errors
  CI = "false"
  
  # Node.js version to use
  NODE_VERSION = "18"

# Redirect rules for single-page applications
# This ensures that all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
